# frozen_string_literal: true

# This file is part of konto_check_ruby, a Ruby port of the C library
# konto_check, Copyright (C) 2002-2023 Michael Plugge <konto_check@yahoo.com>.
# Ruby port Copyright (C) 2026 tickettoaster GmbH <https://tickettoaster.de>.
#
# konto_check_ruby is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or (at
# your option) any later version. It is distributed WITHOUT ANY WARRANTY; see
# the file LICENSE for details.

# Generated from konto_check.h / retvals.h of konto_check 6.15 (Michael Plugge, LGPL).
# Return codes and their textual descriptions.
module KontoCheckRuby
  NO_SCL_BLOCKS_LOADED = -158
  NO_SCL_INFO_BLOCK = -157
  SCL_BIC_NOT_FOUND = -156
  INVALID_SCL_INFO_BLOCK = -155
  NO_SCL_BLOCKS = -154
  SCL_INPUT_FORMAT_ERROR = -153
  INVALID_REGULAR_EXPRESSION_CNT = -152
  INVALID_REGULAR_EXPRESSION = -151
  INVALID_HANDLE = -150
  INVALID_BIQ_INDEX = -149
  ARRAY_INDEX_OUT_OF_RANGE = -148
  IBAN_ONLY_GERMAN = -147
  INVALID_PARAMETER_TYPE = -146
  BIC_ONLY_GERMAN = -145
  INVALID_BIC_LENGTH = -144
  IBAN_CHKSUM_OK_RULE_IGNORED_BLZ = -143
  IBAN_CHKSUM_OK_KC_NOT_INITIALIZED = -142
  IBAN_CHKSUM_OK_BLZ_INVALID = -141
  IBAN_CHKSUM_OK_NACHFOLGE_BLZ_DEFINED = -140
  LUT2_NOT_ALL_IBAN_BLOCKS_LOADED = -139
  LUT2_NOT_YET_VALID_PARTIAL_OK = -138
  LUT2_NO_LONGER_VALID_PARTIAL_OK = -137
  LUT2_BLOCKS_MISSING = -136
  FALSE_UNTERKONTO_ATTACHED = -135
  BLZ_BLACKLISTED = -134
  BLZ_MARKED_AS_DELETED = -133
  IBAN_CHKSUM_OK_SOMETHING_WRONG = -132
  IBAN_CHKSUM_OK_NO_IBAN_CALCULATION = -131
  IBAN_CHKSUM_OK_RULE_IGNORED = -130
  IBAN_CHKSUM_OK_UNTERKTO_MISSING = -129
  IBAN_INVALID_RULE = -128
  IBAN_AMBIGUOUS_KTO = -127
  IBAN_RULE_NOT_IMPLEMENTED = -126
  IBAN_RULE_UNKNOWN = -125
  NO_IBAN_CALCULATION = -124
  OLD_BLZ_OK_NEW_NOT = -123
  LUT2_IBAN_REGEL_NOT_INITIALIZED = -122
  INVALID_IBAN_LENGTH = -121
  LUT2_NO_ACCOUNT_GIVEN = -120
  LUT2_VOLLTEXT_INVALID_CHAR = -119
  LUT2_VOLLTEXT_SINGLE_WORD_ONLY = -118
  LUT_SUCHE_INVALID_RSC = -117
  LUT_SUCHE_INVALID_CMD = -116
  LUT_SUCHE_INVALID_CNT = -115
  LUT2_VOLLTEXT_NOT_INITIALIZED = -114
  NO_OWN_IBAN_CALCULATION = -113
  KTO_CHECK_UNSUPPORTED_COMPRESSION = -112
  KTO_CHECK_INVALID_COMPRESSION_LIB = -111
  OK_UNTERKONTO_ATTACHED_OLD = -110
  KTO_CHECK_DEFAULT_BLOCK_INVALID = -109
  KTO_CHECK_DEFAULT_BLOCK_FULL = -108
  KTO_CHECK_NO_DEFAULT_BLOCK = -107
  KTO_CHECK_KEY_NOT_FOUND = -106
  LUT2_NO_LONGER_VALID_BETTER = -105
  INVALID_SEARCH_RANGE = -79
  KEY_NOT_FOUND = -78
  BAV_FALSE = -77
  LUT2_NO_USER_BLOCK = -76
  INVALID_SET = -75
  NO_GERMAN_BIC = -74
  IPI_CHECK_INVALID_LENGTH = -73
  IPI_INVALID_CHARACTER = -72
  IPI_INVALID_LENGTH = -71
  LUT1_FILE_USED = -70
  MISSING_PARAMETER = -69
  IBAN2BIC_ONLY_GERMAN = -68
  IBAN_OK_KTO_NOT = -67
  KTO_OK_IBAN_NOT = -66
  TOO_MANY_SLOTS = -65
  INIT_FATAL_ERROR = -64
  INCREMENTAL_INIT_NEEDS_INFO = -63
  INCREMENTAL_INIT_FROM_DIFFERENT_FILE = -62
  DEBUG_ONLY_FUNCTION = -61
  LUT2_INVALID = -60
  LUT2_NOT_YET_VALID = -59
  LUT2_NO_LONGER_VALID = -58
  LUT2_GUELTIGKEIT_SWAPPED = -57
  LUT2_INVALID_GUELTIGKEIT = -56
  LUT2_INDEX_OUT_OF_RANGE = -55
  LUT2_INIT_IN_PROGRESS = -54
  LUT2_BLZ_NOT_INITIALIZED = -53
  LUT2_FILIALEN_NOT_INITIALIZED = -52
  LUT2_NAME_NOT_INITIALIZED = -51
  LUT2_PLZ_NOT_INITIALIZED = -50
  LUT2_ORT_NOT_INITIALIZED = -49
  LUT2_NAME_KURZ_NOT_INITIALIZED = -48
  LUT2_PAN_NOT_INITIALIZED = -47
  LUT2_BIC_NOT_INITIALIZED = -46
  LUT2_PZ_NOT_INITIALIZED = -45
  LUT2_NR_NOT_INITIALIZED = -44
  LUT2_AENDERUNG_NOT_INITIALIZED = -43
  LUT2_LOESCHUNG_NOT_INITIALIZED = -42
  LUT2_NACHFOLGE_BLZ_NOT_INITIALIZED = -41
  LUT2_NOT_INITIALIZED = -40
  LUT2_FILIALEN_MISSING = -39
  LUT2_PARTIAL_OK = -38
  LUT2_Z_BUF_ERROR = -37
  LUT2_Z_MEM_ERROR = -36
  LUT2_Z_DATA_ERROR = -35
  LUT2_BLOCK_NOT_IN_FILE = -34
  LUT2_DECOMPRESS_ERROR = -33
  LUT2_COMPRESS_ERROR = -32
  LUT2_FILE_CORRUPTED = -31
  LUT2_NO_SLOT_FREE = -30
  UNDEFINED_SUBMETHOD = -29
  EXCLUDED_AT_COMPILETIME = -28
  INVALID_LUT_VERSION = -27
  INVALID_PARAMETER_STELLE1 = -26
  INVALID_PARAMETER_COUNT = -25
  INVALID_PARAMETER_PRUEFZIFFER = -24
  INVALID_PARAMETER_WICHTUNG = -23
  INVALID_PARAMETER_METHODE = -22
  LIBRARY_INIT_ERROR = -21
  LUT_CRC_ERROR = -20
  FALSE_GELOESCHT = -19
  OK_NO_CHK_GELOESCHT = -18
  OK_GELOESCHT = -17
  BLZ_GELOESCHT = -16
  INVALID_BLZ_FILE = -15
  LIBRARY_IS_NOT_THREAD_SAFE = -14
  FATAL_ERROR = -13
  INVALID_KTO_LENGTH = -12
  FILE_WRITE_ERROR = -11
  FILE_READ_ERROR = -10
  ERROR_MALLOC = -9
  NO_BLZ_FILE = -8
  INVALID_LUT_FILE = -7
  NO_LUT_FILE = -6
  INVALID_BLZ_LENGTH = -5
  INVALID_BLZ = -4
  INVALID_KTO = -3
  NOT_IMPLEMENTED = -2
  NOT_DEFINED = -1
  FALSE = 0
  COMPRESSION_NONE = 1
  LUT2_BLZ = 1
  OK = 1
  COMPRESSION_ZLIB = 2
  LUT2_FILIALEN = 2
  LUT_SUCHE_BIC = 2
  OK_NO_CHK = 2
  COMPRESSION_BZIP2 = 3
  DEFAULT_LUT_VERSION = 3
  LUT2_NAME = 3
  LUT_SUCHE_NAMEN = 3
  OK_TEST_BLZ_USED = 3
  COMPRESSION_LZO = 4
  LUT2_PLZ = 4
  LUT2_VALID = 4
  LUT_SUCHE_NAMEN_KURZ = 4
  COMPRESSION_LZMA = 5
  DEFAULT_INIT_LEVEL = 5
  LUT2_NO_VALID_DATE = 5
  LUT2_ORT = 5
  LUT_SUCHE_ORT = 5
  LUT1_SET_LOADED = 6
  LUT2_NAME_KURZ = 6
  LUT_SUCHE_BLZ = 6
  LUT1_FILE_GENERATED = 7
  LUT2_PAN = 7
  LUT_SUCHE_PLZ = 7
  LUT2_BIC = 8
  LUT_SUCHE_PZ = 8
  DEFAULT_LUT_FIELDS_NUM = 9
  LUT2_PZ = 9
  LUT_SUCHE_REGEL = 9
  LUT_V2_FILE_GENERATED = 9
  KTO_CHECK_VALUE_REPLACED = 10
  LUT2_NR = 10
  LUT_SUCHE_BIC_H = 10
  LUT2_AENDERUNG = 11
  OK_UNTERKONTO_POSSIBLE = 11
  LUT2_LOESCHUNG = 12
  OK_UNTERKONTO_GIVEN = 12
  LUT2_NACHFOLGE_BLZ = 13
  OK_SLOT_CNT_MIN_USED = 13
  LUT2_NAME_NAME_KURZ = 14
  SOME_KEYS_NOT_FOUND = 14
  LUT2_INFO = 15
  LUT2_KTO_NOT_CHECKED = 15
  LUT2_BIC_SORT = 16
  LUT2_OK_WITHOUT_IBAN_RULES = 16
  LUT2_NAME_SORT = 17
  OK_NACHFOLGE_BLZ_USED = 17
  LUT2_NAME_KURZ_SORT = 18
  OK_KTO_REPLACED = 18
  LUT2_ORT_SORT = 19
  OK_BLZ_REPLACED = 19
  LUT2_PLZ_SORT = 20
  OK_BLZ_KTO_REPLACED = 20
  LUT2_PZ_SORT = 21
  OK_IBAN_WITHOUT_KC_TEST = 21
  LUT2_OWN_IBAN = 22
  OK_INVALID_FOR_IBAN = 22
  LUT2_VOLLTEXT_TXT = 23
  OK_HYPO_REQUIRES_KTO = 23
  LUT2_VOLLTEXT_IDX = 24
  OK_KTO_REPLACED_NO_PZ = 24
  LUT2_IBAN_REGEL = 25
  OK_UNTERKONTO_ATTACHED = 25
  LUT2_IBAN_REGEL_SORT = 26
  OK_SHORT_BIC_USED = 26
  LUT2_BIC_H_SORT = 27
  OK_SCL_EXTENSION_BIC_USED = 27
  LUT2_SCL_INFO = 28
  OK_SCL_WILDCARD_BIC_USED = 28
  LUT2_SCL_BIC = 29
  LUT2_SCL_NAME = 30
  LUT2_SCL_FLAGS = 31
  LUT2_SCL_FLAGS_ORIG = 32
  DEFAULT_SLOTS = 60
  SLOT_CNT_MIN = 60
  LAST_LUT_BLOCK = 100
  LUT2_2_BLZ = 101
  LUT2_2_FILIALEN = 102
  LUT2_2_NAME = 103
  LUT2_2_PLZ = 104
  LUT2_2_ORT = 105
  LUT2_2_NAME_KURZ = 106
  LUT2_2_PAN = 107
  LUT2_2_BIC = 108
  LUT2_2_PZ = 109
  LUT2_2_NR = 110
  LUT2_2_AENDERUNG = 111
  LUT2_2_LOESCHUNG = 112
  LUT2_2_NACHFOLGE_BLZ = 113
  LUT2_2_NAME_NAME_KURZ = 114
  LUT2_2_INFO = 115
  LUT2_2_BIC_SORT = 116
  LUT2_2_NAME_SORT = 117
  LUT2_2_NAME_KURZ_SORT = 118
  LUT2_2_ORT_SORT = 119
  LUT2_2_PLZ_SORT = 120
  LUT2_2_PZ_SORT = 121
  LUT2_2_OWN_IBAN = 122
  LUT2_2_VOLLTEXT_TXT = 123
  LUT2_2_VOLLTEXT_IDX = 124
  LUT2_2_IBAN_REGEL = 125
  LUT2_2_IBAN_REGEL_SORT = 126
  LUT2_2_BIC_H_SORT = 127
  LUT2_2_SCL_INFO = 128
  LUT2_2_SCL_BIC = 129
  LUT2_2_SCL_NAME = 130
  LUT2_2_SCL_FLAGS = 131
  LUT2_2_SCL_FLAGS_ORIG = 132
  LUT2_DEFAULT = 501

  # Return-code -> C macro name
  RETVAL_SHORT = {
    -158 => "NO_SCL_BLOCKS_LOADED",
    -157 => "NO_SCL_INFO_BLOCK",
    -156 => "SCL_BIC_NOT_FOUND",
    -155 => "INVALID_SCL_INFO_BLOCK",
    -154 => "NO_SCL_BLOCKS",
    -153 => "SCL_INPUT_FORMAT_ERROR",
    -152 => "INVALID_REGULAR_EXPRESSION_CNT",
    -151 => "INVALID_REGULAR_EXPRESSION",
    -150 => "INVALID_HANDLE",
    -149 => "INVALID_BIQ_INDEX",
    -148 => "ARRAY_INDEX_OUT_OF_RANGE",
    -147 => "IBAN_ONLY_GERMAN",
    -146 => "INVALID_PARAMETER_TYPE",
    -145 => "BIC_ONLY_GERMAN",
    -144 => "INVALID_BIC_LENGTH",
    -143 => "IBAN_CHKSUM_OK_RULE_IGNORED_BLZ",
    -142 => "IBAN_CHKSUM_OK_KC_NOT_INITIALIZED",
    -141 => "IBAN_CHKSUM_OK_BLZ_INVALID",
    -140 => "IBAN_CHKSUM_OK_NACHFOLGE_BLZ_DEFINED",
    -139 => "LUT2_NOT_ALL_IBAN_BLOCKS_LOADED",
    -138 => "LUT2_NOT_YET_VALID_PARTIAL_OK",
    -137 => "LUT2_NO_LONGER_VALID_PARTIAL_OK",
    -136 => "LUT2_BLOCKS_MISSING",
    -135 => "FALSE_UNTERKONTO_ATTACHED",
    -134 => "BLZ_BLACKLISTED",
    -133 => "BLZ_MARKED_AS_DELETED",
    -132 => "IBAN_CHKSUM_OK_SOMETHING_WRONG",
    -131 => "IBAN_CHKSUM_OK_NO_IBAN_CALCULATION",
    -130 => "IBAN_CHKSUM_OK_RULE_IGNORED",
    -129 => "IBAN_CHKSUM_OK_UNTERKTO_MISSING",
    -128 => "IBAN_INVALID_RULE",
    -127 => "IBAN_AMBIGUOUS_KTO",
    -126 => "IBAN_RULE_NOT_IMPLEMENTED",
    -125 => "IBAN_RULE_UNKNOWN",
    -124 => "NO_IBAN_CALCULATION",
    -123 => "OLD_BLZ_OK_NEW_NOT",
    -122 => "LUT2_IBAN_REGEL_NOT_INITIALIZED",
    -121 => "INVALID_IBAN_LENGTH",
    -120 => "LUT2_NO_ACCOUNT_GIVEN",
    -119 => "LUT2_VOLLTEXT_INVALID_CHAR",
    -118 => "LUT2_VOLLTEXT_SINGLE_WORD_ONLY",
    -117 => "LUT_SUCHE_INVALID_RSC",
    -116 => "LUT_SUCHE_INVALID_CMD",
    -115 => "LUT_SUCHE_INVALID_CNT",
    -114 => "LUT2_VOLLTEXT_NOT_INITIALIZED",
    -113 => "NO_OWN_IBAN_CALCULATION",
    -112 => "KTO_CHECK_UNSUPPORTED_COMPRESSION",
    -111 => "KTO_CHECK_INVALID_COMPRESSION_LIB",
    -110 => "OK_UNTERKONTO_ATTACHED_OLD",
    -109 => "KTO_CHECK_DEFAULT_BLOCK_INVALID",
    -108 => "KTO_CHECK_DEFAULT_BLOCK_FULL",
    -107 => "KTO_CHECK_NO_DEFAULT_BLOCK",
    -106 => "KTO_CHECK_KEY_NOT_FOUND",
    -105 => "LUT2_NO_LONGER_VALID_BETTER",
    -79 => "INVALID_SEARCH_RANGE",
    -78 => "KEY_NOT_FOUND",
    -77 => "BAV_FALSE",
    -76 => "LUT2_NO_USER_BLOCK",
    -75 => "INVALID_SET",
    -74 => "NO_GERMAN_BIC",
    -73 => "IPI_CHECK_INVALID_LENGTH",
    -72 => "IPI_INVALID_CHARACTER",
    -71 => "IPI_INVALID_LENGTH",
    -70 => "LUT1_FILE_USED",
    -69 => "MISSING_PARAMETER",
    -68 => "IBAN2BIC_ONLY_GERMAN",
    -67 => "IBAN_OK_KTO_NOT",
    -66 => "KTO_OK_IBAN_NOT",
    -65 => "TOO_MANY_SLOTS",
    -64 => "INIT_FATAL_ERROR",
    -63 => "INCREMENTAL_INIT_NEEDS_INFO",
    -62 => "INCREMENTAL_INIT_FROM_DIFFERENT_FILE",
    -61 => "DEBUG_ONLY_FUNCTION",
    -60 => "LUT2_INVALID",
    -59 => "LUT2_NOT_YET_VALID",
    -58 => "LUT2_NO_LONGER_VALID",
    -57 => "LUT2_GUELTIGKEIT_SWAPPED",
    -56 => "LUT2_INVALID_GUELTIGKEIT",
    -55 => "LUT2_INDEX_OUT_OF_RANGE",
    -54 => "LUT2_INIT_IN_PROGRESS",
    -53 => "LUT2_BLZ_NOT_INITIALIZED",
    -52 => "LUT2_FILIALEN_NOT_INITIALIZED",
    -51 => "LUT2_NAME_NOT_INITIALIZED",
    -50 => "LUT2_PLZ_NOT_INITIALIZED",
    -49 => "LUT2_ORT_NOT_INITIALIZED",
    -48 => "LUT2_NAME_KURZ_NOT_INITIALIZED",
    -47 => "LUT2_PAN_NOT_INITIALIZED",
    -46 => "LUT2_BIC_NOT_INITIALIZED",
    -45 => "LUT2_PZ_NOT_INITIALIZED",
    -44 => "LUT2_NR_NOT_INITIALIZED",
    -43 => "LUT2_AENDERUNG_NOT_INITIALIZED",
    -42 => "LUT2_LOESCHUNG_NOT_INITIALIZED",
    -41 => "LUT2_NACHFOLGE_BLZ_NOT_INITIALIZED",
    -40 => "LUT2_NOT_INITIALIZED",
    -39 => "LUT2_FILIALEN_MISSING",
    -38 => "LUT2_PARTIAL_OK",
    -37 => "LUT2_Z_BUF_ERROR",
    -36 => "LUT2_Z_MEM_ERROR",
    -35 => "LUT2_Z_DATA_ERROR",
    -34 => "LUT2_BLOCK_NOT_IN_FILE",
    -33 => "LUT2_DECOMPRESS_ERROR",
    -32 => "LUT2_COMPRESS_ERROR",
    -31 => "LUT2_FILE_CORRUPTED",
    -30 => "LUT2_NO_SLOT_FREE",
    -29 => "UNDEFINED_SUBMETHOD",
    -28 => "EXCLUDED_AT_COMPILETIME",
    -27 => "INVALID_LUT_VERSION",
    -26 => "INVALID_PARAMETER_STELLE1",
    -25 => "INVALID_PARAMETER_COUNT",
    -24 => "INVALID_PARAMETER_PRUEFZIFFER",
    -23 => "INVALID_PARAMETER_WICHTUNG",
    -22 => "INVALID_PARAMETER_METHODE",
    -21 => "LIBRARY_INIT_ERROR",
    -20 => "LUT_CRC_ERROR",
    -19 => "FALSE_GELOESCHT",
    -18 => "OK_NO_CHK_GELOESCHT",
    -17 => "OK_GELOESCHT",
    -16 => "BLZ_GELOESCHT",
    -15 => "INVALID_BLZ_FILE",
    -14 => "LIBRARY_IS_NOT_THREAD_SAFE",
    -13 => "FATAL_ERROR",
    -12 => "INVALID_KTO_LENGTH",
    -11 => "FILE_WRITE_ERROR",
    -10 => "FILE_READ_ERROR",
    -9 => "ERROR_MALLOC",
    -8 => "NO_BLZ_FILE",
    -7 => "INVALID_LUT_FILE",
    -6 => "NO_LUT_FILE",
    -5 => "INVALID_BLZ_LENGTH",
    -4 => "INVALID_BLZ",
    -3 => "INVALID_KTO",
    -2 => "NOT_IMPLEMENTED",
    -1 => "NOT_DEFINED",
    0 => "FALSE",
    1 => "OK",
    2 => "OK_NO_CHK",
    3 => "OK_TEST_BLZ_USED",
    4 => "LUT2_VALID",
    5 => "LUT2_NO_VALID_DATE",
    6 => "LUT1_SET_LOADED",
    7 => "LUT1_FILE_GENERATED",
    9 => "LUT_V2_FILE_GENERATED",
    10 => "KTO_CHECK_VALUE_REPLACED",
    11 => "OK_UNTERKONTO_POSSIBLE",
    12 => "OK_UNTERKONTO_GIVEN",
    13 => "OK_SLOT_CNT_MIN_USED",
    14 => "SOME_KEYS_NOT_FOUND",
    15 => "LUT2_KTO_NOT_CHECKED",
    16 => "LUT2_OK_WITHOUT_IBAN_RULES",
    17 => "OK_NACHFOLGE_BLZ_USED",
    18 => "OK_KTO_REPLACED",
    19 => "OK_BLZ_REPLACED",
    20 => "OK_BLZ_KTO_REPLACED",
    21 => "OK_IBAN_WITHOUT_KC_TEST",
    22 => "OK_INVALID_FOR_IBAN",
    23 => "OK_HYPO_REQUIRES_KTO",
    24 => "OK_KTO_REPLACED_NO_PZ",
    25 => "OK_UNTERKONTO_ATTACHED",
    26 => "OK_SHORT_BIC_USED",
    27 => "OK_SCL_EXTENSION_BIC_USED",
    28 => "OK_SCL_WILDCARD_BIC_USED",
  }.freeze

  # Return-code -> German description (UTF-8)
  RETVAL_TEXT = {
    -158 => "die SCL-Blocks wurden noch nicht eingelesen",
    -157 => "Der Info-Block des SCL-Verzeichnisses wurde noch nicht eingelesen",
    -156 => "Der BIC wurde im SCL-Verzeichnis nicht gefunden",
    -155 => "Ungültiger SCL-Info-Block in der LUT-Datei",
    -154 => "Keine SCL-Blocks in der LUT-Datei enthalten",
    -153 => "Ungültige Eingabewerte in der SCL-Datei",
    -152 => "Ungültiger Zähler in regulärem Ausdruck (innerhalb von {})",
    -151 => "Ungültiger regulärer Ausdruck (enthält zwei Zeichen aus [+?*] nacheinander)",
    -150 => "Ungültiges Handle angegeben",
    -149 => "Ungültiger Index für die biq_*() Funktionen",
    -148 => "Der Array-Index liegt außerhalb des gültigen Bereichs",
    -147 => "Es werden nur deutsche IBANs unterstützt",
    -146 => "Falscher Parametertyp für die Funktion",
    -145 => "Es werden nur deutsche BICs unterstützt",
    -144 => "Die Länge des BIC muß genau 8 oder 11 Zeichen sein",
    -143 => "Die IBAN-Prüfsumme stimmt, die BLZ sollte aber durch eine zentrale BLZ ersetzt werden. Die Richtigkeit der IBAN kann nur mit einer Anfrage bei der Bank ermittelt werden",
    -142 => "Die IBAN-Prüfsumme stimmt, konto_check wurde jedoch noch nicht initialisiert (Kontoprüfung nicht möglich)",
    -141 => "Die IBAN-Prüfsumme stimmt, die BLZ ist allerdings ungültig",
    -140 => "Die IBAN-Prüfsumme stimmt, für die Bank gibt es allerdings eine (andere) Nachfolge-BLZ",
    -139 => "es konnten nicht alle Datenblocks die für die IBAN-Berechnung notwendig sind geladen werden",
    -138 => "Der Datensatz ist noch nicht gültig, außerdem konnten nicht alle Blocks geladen werden",
    -137 => "Der Datensatz ist nicht mehr gültig, außerdem konnten nicht alle Blocks geladen werdeng",
    -136 => "ok, bei der Initialisierung konnten allerdings ein oder mehrere Blocks nicht geladen werden",
    -135 => "falsch, es wurde ein Unterkonto hinzugefügt (IBAN-Regel)",
    -134 => "Die BLZ findet sich in der Ausschlussliste für IBAN-Berechnungen",
    -133 => "Die BLZ ist in der Bundesbank-Datei als gelöscht markiert und somit ungültig",
    -132 => "Die IBAN-Prüfsumme stimmt, es gibt allerdings einen Fehler in der eigenen IBAN-Bestimmung (wahrscheinlich falsch)",
    -131 => "Die IBAN-Prüfsumme stimmt. Die Bank gibt IBANs nach nicht veröffentlichten Regeln heraus, die Richtigkeit der IBAN kann nur mit einer Anfrage bei der Bank ermittelt werden",
    -130 => "Die IBAN-Prüfsumme stimmt, es wurde allerdings eine IBAN-Regel nicht beachtet (wahrscheinlich falsch)",
    -129 => "Die IBAN-Prüfsumme stimmt, es fehlt aber ein Unterkonto (wahrscheinlich falsch)",
    -128 => "Die BLZ passt nicht zur angegebenen IBAN-Regel",
    -127 => "Die Kontonummer ist nicht eindeutig (es gibt mehrere Möglichkeiten)",
    -126 => "Die IBAN-Regel ist noch nicht implementiert",
    -125 => "Die IBAN-Regel ist nicht bekannt",
    -124 => "Für die Bankverbindung ist keine IBAN-Berechnung erlaubt",
    -123 => "Die Bankverbindung ist mit der alten BLZ stimmig, mit der Nachfolge-BLZ nicht",
    -122 => "Das Feld IBAN-Regel wurde nicht initialisiert",
    -121 => "Die Länge der IBAN für das angegebene Länderkürzel ist falsch",
    -120 => "Keine Bankverbindung/IBAN angegeben",
    -119 => "Ungültiges Zeichen ( ()+-/&.,\\' ) für die Volltextsuche gefunden",
    -118 => "Die Volltextsuche sucht jeweils nur ein einzelnes Wort, benutzen Sie lut_suche_multiple() zur Suche nach mehreren Worten",
    -117 => "die angegebene Suchresource ist ungültig",
    -116 => "bei der Suche sind im Verknüpfungsstring nur die Zeichen a-z sowie + und - erlaubt",
    -115 => "bei der Suche müssen zwischen 1 und 26 Suchmuster angegeben werden",
    -114 => "Das Feld Volltext wurde nicht initialisiert",
    -113 => "das Institut erlaubt keine eigene IBAN-Berechnung",
    -112 => "die notwendige Kompressions-Bibliothek wurde beim Kompilieren nicht eingebunden",
    -111 => "der angegebene Wert für die Default-Kompression ist ungültig",
    -110 => "(nicht mehr als Fehler, sondern positive Ausgabe - Dummy für den alten Wert)",
    -109 => "Ungültige Signatur im Default-Block",
    -108 => "Die maximale Anzahl Einträge für den Default-Block wurde erreicht",
    -107 => "Es wurde noch kein Default-Block angelegt",
    -106 => "Der angegebene Schlüssel wurde im Default-Block nicht gefunden",
    -105 => "Beide Datensätze sind nicht mehr gültig, dieser ist aber jünger als der andere",
    -79 => "ungültiger Suchbereich angegeben (unten>oben)",
    -78 => "Die Suche lieferte kein Ergebnis",
    -77 => "BAV denkt, das Konto ist falsch (konto_check hält es für richtig)",
    -76 => "User-Blocks müssen einen Typ > 500 haben",
    -75 => "für ein LUT-Set sind nur die Werte 0, 1 oder 2 möglich",
    -74 => "Ein Konto kann kann nur für deutsche Banken geprüft werden",
    -73 => "Der zu validierende strukturierete Verwendungszweck muß genau 20 Zeichen enthalten",
    -72 => "Im strukturierten Verwendungszweck dürfen nur alphanumerische Zeichen vorkommen",
    -71 => "Die Länge des IPI-Verwendungszwecks darf maximal 18 Byte sein",
    -70 => "Es wurde eine LUT-Datei im Format 1.0/1.1 geladen",
    -69 => "Für die aufgerufene Funktion fehlt ein notwendiger Parameter",
    -68 => "Die Funktion iban2bic() arbeitet nur mit deutschen Bankleitzahlen",
    -67 => "Die Prüfziffer der IBAN stimmt, die der Kontonummer nicht",
    -66 => "Die Prüfziffer der Kontonummer stimmt, die der IBAN nicht",
    -65 => "Es sind nur maximal 500 Slots pro LUT-Datei möglich (Neukompilieren erforderlich)",
    -64 => "Initialisierung fehlgeschlagen (init_wait geblockt)",
    -63 => "Ein inkrementelles Initialisieren benötigt einen Info-Block in der LUT-Datei",
    -62 => "Ein inkrementelles Initialisieren mit einer anderen LUT-Datei ist nicht möglich",
    -61 => "Die Funktion ist nur in der Debug-Version vorhanden",
    -60 => "Kein Datensatz der LUT-Datei ist aktuell gültig",
    -59 => "Der Datensatz ist noch nicht gültig",
    -58 => "Der Datensatz ist nicht mehr gültig",
    -57 => "Im Gültigkeitsdatum sind Anfangs- und Enddatum vertauscht",
    -56 => "Das angegebene Gültigkeitsdatum ist ungültig (Sollformat ist JJJJMMTT-JJJJMMTT)",
    -55 => "Der Index für die Filiale ist ungültig",
    -54 => "Die Bibliothek wird gerade neu initialisiert",
    -53 => "Das Feld BLZ wurde nicht initialisiert",
    -52 => "Das Feld Filialen wurde nicht initialisiert",
    -51 => "Das Feld Bankname wurde nicht initialisiert",
    -50 => "Das Feld PLZ wurde nicht initialisiert",
    -49 => "Das Feld Ort wurde nicht initialisiert",
    -48 => "Das Feld Kurzname wurde nicht initialisiert",
    -47 => "Das Feld PAN wurde nicht initialisiert",
    -46 => "Das Feld BIC wurde nicht initialisiert",
    -45 => "Das Feld Prüfziffer wurde nicht initialisiert",
    -44 => "Das Feld NR wurde nicht initialisiert",
    -43 => "Das Feld Änderung wurde nicht initialisiert",
    -42 => "Das Feld Löschung wurde nicht initialisiert",
    -41 => "Das Feld Nachfolge-BLZ wurde nicht initialisiert",
    -40 => "die Programmbibliothek wurde noch nicht initialisiert",
    -39 => "der Block mit der Filialenanzahl fehlt in der LUT-Datei",
    -38 => "es wurden nicht alle Blocks geladen",
    -37 => "Buffer error in den ZLIB Routinen",
    -36 => "Memory error in den ZLIB-Routinen",
    -35 => "Datenfehler im komprimierten LUT-Block",
    -34 => "Der Block ist nicht in der LUT-Datei enthalten",
    -33 => "Fehler beim Dekomprimieren eines LUT-Blocks",
    -32 => "Fehler beim Komprimieren eines LUT-Blocks",
    -31 => "Die LUT-Datei ist korrumpiert",
    -30 => "Im Inhaltsverzeichnis der LUT-Datei ist kein Slot mehr frei",
    -29 => "Die (Unter)Methode ist nicht definiert",
    -28 => "Der benötigte Programmteil wurde beim Kompilieren deaktiviert",
    -27 => "Die Versionsnummer für die LUT-Datei ist ungültig",
    -26 => "ungültiger Prüfparameter (erste zu prüfende Stelle)",
    -25 => "ungültiger Prüfparameter (Anzahl zu prüfender Stellen)",
    -24 => "ungültiger Prüfparameter (Position der Prüfziffer)",
    -23 => "ungültiger Prüfparameter (Wichtung)",
    -22 => "ungültiger Prüfparameter (Rechenmethode)",
    -21 => "Problem beim Initialisieren der globalen Variablen",
    -20 => "Prüfsummenfehler in der blz.lut Datei",
    -19 => "falsch (die BLZ wurde außerdem gelöscht)",
    -18 => "ok, ohne Prüfung (die BLZ wurde allerdings gelöscht)",
    -17 => "ok (die BLZ wurde allerdings gelöscht)",
    -16 => "die Bankleitzahl wurde gelöscht",
    -15 => "Fehler in der blz.txt Datei (falsche Zeilenlänge)",
    -14 => "undefinierte Funktion, die library wurde mit THREAD_SAFE=0 kompiliert",
    -13 => "schwerer Fehler im Konto_check-Modul",
    -12 => "ein Konto muß zwischen 1 und 10 Stellen haben",
    -11 => "kann Datei nicht schreiben",
    -10 => "kann Datei nicht lesen",
    -9 => "kann keinen Speicher allokieren",
    -8 => "die blz.txt Datei wurde nicht gefunden",
    -7 => "die blz.lut Datei ist inkosistent/ungültig",
    -6 => "die blz.lut Datei wurde nicht gefunden",
    -5 => "die Bankleitzahl ist nicht achtstellig",
    -4 => "die Bankleitzahl ist ungültig",
    -3 => "das Konto ist ungültig",
    -2 => "die Methode wurde noch nicht implementiert",
    -1 => "die Methode ist nicht definiert",
    0 => "falsch",
    1 => "ok",
    2 => "ok, ohne Prüfung",
    3 => "ok, für den Test wurde eine Test-BLZ verwendet",
    4 => "Der Datensatz ist aktuell gültig",
    5 => "Der Datensatz enthält kein Gültigkeitsdatum",
    6 => "Die Datei ist im alten LUT-Format (1.0/1.1)",
    7 => "ok, es wurde allerdings eine LUT-Datei im alten Format (1.0/1.1) generiert",
    9 => "ok, es wurde allerdings eine LUT-Datei im Format 2.0 generiert (Compilerswitch)",
    10 => "ok, der Wert für den Schlüssel wurde überschrieben",
    11 => "wahrscheinlich ok, die Kontonummer kann allerdings (nicht angegebene) Unterkonten enthalten",
    12 => "wahrscheinlich ok, die Kontonummer enthält eine Unterkontonummer",
    13 => "ok, die Anzahl Slots wurde auf SLOT_CNT_MIN (60) hochgesetzt",
    14 => "ok, ein(ige) Schlüssel wurden nicht gefunden",
    15 => "Die Bankverbindung wurde nicht getestet",
    16 => "Es wurden fast alle Blocks (außer den IBAN-Regeln) geladen",
    17 => "ok, für die BLZ wurde allerdings die Nachfolge-BLZ eingesetzt",
    18 => "ok, die Kontonummer wurde allerdings ersetzt",
    19 => "ok, die Bankleitzahl wurde allerdings ersetzt",
    20 => "ok, die Bankleitzahl und Kontonummer wurden allerdings ersetzt",
    21 => "ok, die Bankverbindung ist (ohne Test) als richtig anzusehen",
    22 => "ok, für die die IBAN ist (durch eine Regel) allerdings ein anderer BIC definiert",
    23 => "ok, für die BIC-Bestimmung der ehemaligen Hypo-Bank für IBAN wird i.A. zusätzlich die Kontonummer benötigt",
    24 => "ok, die Kontonummer wurde ersetzt, die neue Kontonummer hat keine Prüfziffer",
    25 => "ok, es wurde ein (weggelassenes) Unterkonto angefügt",
    26 => "ok, für den BIC wurde die Zweigstellennummer allerdings durch XXX ersetzt",
    27 => "ok, für den BIC wurde die Extension XXX angehängt",
    28 => "ok, für den BIC wurde die Wildcard-Version (8stellig) benutzt",
  }.freeze

  # Return-code -> German description with HTML entities
  RETVAL_HTML = {
    -158 => "die SCL-Blocks wurden noch nicht eingelesen",
    -157 => "Der Info-Block des SCL-Verzeichnisses wurde noch nicht eingelesen",
    -156 => "Der BIC wurde im SCL-Verzeichnis nicht gefunden",
    -155 => "Ung&uuml;ltiger SCL-Info-Block in der LUT-Datei",
    -154 => "Keine SCL-Blocks in der LUT-Datei enthalten",
    -153 => "Ung&uuml;ltige Eingabewerte in der SCL-Datei",
    -152 => "Ung&uuml;ltiger Z&auml;hler in regul&auml;rem Ausdruck (innerhalb von {})",
    -151 => "Ung&uuml;ltiger regul&auml;rer Ausdruck (enth&auml;lt zwei Zeichen aus [+?*] nacheinander)",
    -150 => "Ung&uuml;ltiges Handle angegeben",
    -149 => "Ung&uuml;ltiger Index f&uuml;r die biq_*() Funktionen",
    -148 => "Der Array-Index liegt au&szlig;erhalb des g&uuml;ltigen Bereichs",
    -147 => "Es werden nur deutsche IBANs unterst&uuml;tzt",
    -146 => "Falscher Parametertyp f&uuml;r die Funktion",
    -145 => "Es werden nur deutsche BICs unterst&uuml;tzt",
    -144 => "Die L&auml;nge des BIC mu&szlig; genau 8 oder 11 Zeichen sein",
    -143 => "Die IBAN-Pr&uuml;fsumme stimmt, die BLZ sollte aber durch eine zentrale BLZ ersetzt werden. Die Richtigkeit der IBAN kann nur mit einer Anfrage bei der Bank ermittelt werden",
    -142 => "Die IBAN-Pr&uuml;fsumme stimmt, konto_check wurde jedoch noch nicht initialisiert (Kontopr&uuml;fung nicht m&ouml;glich)",
    -141 => "Die IBAN-Pr&uuml;fsumme stimmt, die BLZ ist allerdings ung&uuml;ltig",
    -140 => "Die IBAN-Pr&uuml;fsumme stimmt, f&uuml;r die Bank gibt es allerdings eine (andere) Nachfolge-BLZ",
    -139 => "es konnten nicht alle Datenblocks die f&uuml;r die IBAN-Berechnung notwendig sind geladen werden",
    -138 => "Der Datensatz ist noch nicht g&uuml;ltig, au&szlig;erdem konnten nicht alle Blocks geladen werden",
    -137 => "Der Datensatz ist nicht mehr g&uuml;ltig, au&szlig;erdem konnten nicht alle Blocks geladen werdeng",
    -136 => "ok, bei der Initialisierung konnten allerdings ein oder mehrere Blocks nicht geladen werden",
    -135 => "falsch, es wurde ein Unterkonto hinzugef&uuml;gt (IBAN-Regel)",
    -134 => "Die BLZ findet sich in der Ausschlussliste f&uuml;r IBAN-Berechnungen",
    -133 => "Die BLZ ist in der Bundesbank-Datei als gel&ouml;scht markiert und somit ung&uuml;ltig",
    -132 => "Die IBAN-Pr&uuml;fsumme stimmt, es gibt allerdings einen Fehler in der eigenen IBAN-Bestimmung (wahrscheinlich falsch)",
    -131 => "Die IBAN-Pr&uuml;fsumme stimmt. Die Bank gibt IBANs nach nicht ver&ouml;ffentlichten Regeln heraus, die Richtigkeit der IBAN kann nur mit einer Anfrage bei der Bank ermittelt werden",
    -130 => "Die IBAN-Pr&uuml;fsumme stimmt, es wurde allerdings eine IBAN-Regel nicht beachtet (wahrscheinlich falsch)",
    -129 => "Die IBAN-Pr&uuml;fsumme stimmt, es fehlt aber ein Unterkonto (wahrscheinlich falsch)",
    -128 => "Die BLZ passt nicht zur angegebenen IBAN-Regel",
    -127 => "Die Kontonummer ist nicht eindeutig (es gibt mehrere M&ouml;glichkeiten)",
    -126 => "Die IBAN-Regel ist noch nicht implementiert",
    -125 => "Die IBAN-Regel ist nicht bekannt",
    -124 => "F&uuml;r die Bankverbindung ist keine IBAN-Berechnung erlaubt",
    -123 => "Die Bankverbindung ist mit der alten BLZ stimmig, mit der Nachfolge-BLZ nicht",
    -122 => "Das Feld IBAN-Regel wurde nicht initialisiert",
    -121 => "Die L&auml;nge der IBAN f&uuml;r das angegebene L&auml;nderk&uuml;rzel ist falsch",
    -120 => "Keine Bankverbindung/IBAN angegeben",
    -119 => "Ung&uuml;ltiges Zeichen ( ()+-/&amp;.,\\' ) f&uuml;r die Volltextsuche gefunden",
    -118 => "Die Volltextsuche sucht jeweils nur ein einzelnes Wort, benutzen Sie lut_suche_multiple() zur Suche nach mehreren Worten",
    -117 => "die angegebene Suchresource ist ung&uuml;ltig",
    -116 => "bei der Suche sind im Verkn&uuml;pfungsstring nur die Zeichen a-z sowie + und - erlaubt",
    -115 => "bei der Suche m&uuml;ssen zwischen 1 und 26 Suchmuster angegeben werden",
    -114 => "Das Feld Volltext wurde nicht initialisiert",
    -113 => "das Institut erlaubt keine eigene IBAN-Berechnung",
    -112 => "die notwendige Kompressions-Bibliothek wurde beim Kompilieren nicht eingebunden",
    -111 => "der angegebene Wert f&uuml;r die Default-Kompression ist ung&uuml;ltig",
    -110 => "(nicht mehr als Fehler, sondern positive Ausgabe - Dummy f&uuml;r den alten Wert)",
    -109 => "Ung&uuml;ltige Signatur im Default-Block",
    -108 => "Die maximale Anzahl Eintr&auml;ge f&uuml;r den Default-Block wurde erreicht",
    -107 => "Es wurde noch kein Default-Block angelegt",
    -106 => "Der angegebene Schl&uuml;ssel wurde im Default-Block nicht gefunden",
    -105 => "Beide Datens&auml;tze sind nicht mehr g&uuml;ltig, dieser ist aber j&uuml;nger als der andere",
    -79 => "ung&uuml;ltiger Suchbereich angegeben (unten&gt;oben)",
    -78 => "Die Suche lieferte kein Ergebnis",
    -77 => "BAV denkt, das Konto ist falsch (konto_check h&auml;lt es f&uuml;r richtig)",
    -76 => "User-Blocks m&uuml;ssen einen Typ &gt; 500 haben",
    -75 => "f&uuml;r ein LUT-Set sind nur die Werte 0, 1 oder 2 m&ouml;glich",
    -74 => "Ein Konto kann kann nur f&uuml;r deutsche Banken gepr&uuml;ft werden",
    -73 => "Der zu validierende strukturierete Verwendungszweck mu&szlig; genau 20 Zeichen enthalten",
    -72 => "Im strukturierten Verwendungszweck d&uuml;rfen nur alphanumerische Zeichen vorkommen",
    -71 => "Die L&auml;nge des IPI-Verwendungszwecks darf maximal 18 Byte sein",
    -70 => "Es wurde eine LUT-Datei im Format 1.0/1.1 geladen",
    -69 => "F&uuml;r die aufgerufene Funktion fehlt ein notwendiger Parameter",
    -68 => "Die Funktion iban2bic() arbeitet nur mit deutschen Bankleitzahlen",
    -67 => "Die Pr&uuml;fziffer der IBAN stimmt, die der Kontonummer nicht",
    -66 => "Die Pr&uuml;fziffer der Kontonummer stimmt, die der IBAN nicht",
    -65 => "Es sind nur maximal 500 Slots pro LUT-Datei m&ouml;glich (Neukompilieren erforderlich)",
    -64 => "Initialisierung fehlgeschlagen (init_wait geblockt)",
    -63 => "Ein inkrementelles Initialisieren ben&ouml;tigt einen Info-Block in der LUT-Datei",
    -62 => "Ein inkrementelles Initialisieren mit einer anderen LUT-Datei ist nicht m&ouml;glich",
    -61 => "Die Funktion ist nur in der Debug-Version vorhanden",
    -60 => "Kein Datensatz der LUT-Datei ist aktuell g&uuml;ltig",
    -59 => "Der Datensatz ist noch nicht g&uuml;ltig",
    -58 => "Der Datensatz ist nicht mehr g&uuml;ltig",
    -57 => "Im G&uuml;ltigkeitsdatum sind Anfangs- und Enddatum vertauscht",
    -56 => "Das angegebene G&uuml;ltigkeitsdatum ist ung&uuml;ltig (Sollformat ist JJJJMMTT-JJJJMMTT)",
    -55 => "Der Index f&uuml;r die Filiale ist ung&uuml;ltig",
    -54 => "Die Bibliothek wird gerade neu initialisiert",
    -53 => "Das Feld BLZ wurde nicht initialisiert",
    -52 => "Das Feld Filialen wurde nicht initialisiert",
    -51 => "Das Feld Bankname wurde nicht initialisiert",
    -50 => "Das Feld PLZ wurde nicht initialisiert",
    -49 => "Das Feld Ort wurde nicht initialisiert",
    -48 => "Das Feld Kurzname wurde nicht initialisiert",
    -47 => "Das Feld PAN wurde nicht initialisiert",
    -46 => "Das Feld BIC wurde nicht initialisiert",
    -45 => "Das Feld Pr&uuml;fziffer wurde nicht initialisiert",
    -44 => "Das Feld NR wurde nicht initialisiert",
    -43 => "Das Feld &Auml;nderung wurde nicht initialisiert",
    -42 => "Das Feld L&ouml;schung wurde nicht initialisiert",
    -41 => "Das Feld Nachfolge-BLZ wurde nicht initialisiert",
    -40 => "die Programmbibliothek wurde noch nicht initialisiert",
    -39 => "der Block mit der Filialenanzahl fehlt in der LUT-Datei",
    -38 => "es wurden nicht alle Blocks geladen",
    -37 => "Buffer error in den ZLIB Routinen",
    -36 => "Memory error in den ZLIB-Routinen",
    -35 => "Datenfehler im komprimierten LUT-Block",
    -34 => "Der Block ist nicht in der LUT-Datei enthalten",
    -33 => "Fehler beim Dekomprimieren eines LUT-Blocks",
    -32 => "Fehler beim Komprimieren eines LUT-Blocks",
    -31 => "Die LUT-Datei ist korrumpiert",
    -30 => "Im Inhaltsverzeichnis der LUT-Datei ist kein Slot mehr frei",
    -29 => "Die (Unter)Methode ist nicht definiert",
    -28 => "Der ben&ouml;tigte Programmteil wurde beim Kompilieren deaktiviert",
    -27 => "Die Versionsnummer f&uuml;r die LUT-Datei ist ung&uuml;ltig",
    -26 => "ung&uuml;ltiger Pr&uuml;fparameter (erste zu pr&uuml;fende Stelle)",
    -25 => "ung&uuml;ltiger Pr&uuml;fparameter (Anzahl zu pr&uuml;fender Stellen)",
    -24 => "ung&uuml;ltiger Pr&uuml;fparameter (Position der Pr&uuml;fziffer)",
    -23 => "ung&uuml;ltiger Pr&uuml;fparameter (Wichtung)",
    -22 => "ung&uuml;ltiger Pr&uuml;fparameter (Rechenmethode)",
    -21 => "Problem beim Initialisieren der globalen Variablen",
    -20 => "Pr&uuml;fsummenfehler in der blz.lut Datei",
    -19 => "falsch (die BLZ wurde au&szlig;erdem gel&ouml;scht)",
    -18 => "ok, ohne Pr&uuml;fung (die BLZ wurde allerdings gel&ouml;scht)",
    -17 => "ok (die BLZ wurde allerdings gel&ouml;scht)",
    -16 => "die Bankleitzahl wurde gel&ouml;scht",
    -15 => "Fehler in der blz.txt Datei (falsche Zeilenl&auml;nge)",
    -14 => "undefinierte Funktion, die library wurde mit THREAD_SAFE=0 kompiliert",
    -13 => "schwerer Fehler im Konto_check-Modul",
    -12 => "ein Konto mu&szlig; zwischen 1 und 10 Stellen haben",
    -11 => "kann Datei nicht schreiben",
    -10 => "kann Datei nicht lesen",
    -9 => "kann keinen Speicher allokieren",
    -8 => "die blz.txt Datei wurde nicht gefunden",
    -7 => "die blz.lut Datei ist inkosistent/ung&uuml;ltig",
    -6 => "die blz.lut Datei wurde nicht gefunden",
    -5 => "die Bankleitzahl ist nicht achtstellig",
    -4 => "die Bankleitzahl ist ung&uuml;ltig",
    -3 => "das Konto ist ung&uuml;ltig",
    -2 => "die Methode wurde noch nicht implementiert",
    -1 => "die Methode ist nicht definiert",
    0 => "falsch",
    1 => "ok",
    2 => "ok, ohne Pr&uuml;fung",
    3 => "ok, f&uuml;r den Test wurde eine Test-BLZ verwendet",
    4 => "Der Datensatz ist aktuell g&uuml;ltig",
    5 => "Der Datensatz enth&auml;lt kein G&uuml;ltigkeitsdatum",
    6 => "Die Datei ist im alten LUT-Format (1.0/1.1)",
    7 => "ok, es wurde allerdings eine LUT-Datei im alten Format (1.0/1.1) generiert",
    9 => "ok, es wurde allerdings eine LUT-Datei im Format 2.0 generiert (Compilerswitch)",
    10 => "ok, der Wert f&uuml;r den Schl&uuml;ssel wurde &uuml;berschrieben",
    11 => "wahrscheinlich ok, die Kontonummer kann allerdings (nicht angegebene) Unterkonten enthalten",
    12 => "wahrscheinlich ok, die Kontonummer enth&auml;lt eine Unterkontonummer",
    13 => "ok, die Anzahl Slots wurde auf SLOT_CNT_MIN (60) hochgesetzt",
    14 => "ok, ein(ige) Schl&uuml;ssel wurden nicht gefunden",
    15 => "Die Bankverbindung wurde nicht getestet",
    16 => "Es wurden fast alle Blocks (au&szlig;er den IBAN-Regeln) geladen",
    17 => "ok, f&uuml;r die BLZ wurde allerdings die Nachfolge-BLZ eingesetzt",
    18 => "ok, die Kontonummer wurde allerdings ersetzt",
    19 => "ok, die Bankleitzahl wurde allerdings ersetzt",
    20 => "ok, die Bankleitzahl und Kontonummer wurden allerdings ersetzt",
    21 => "ok, die Bankverbindung ist (ohne Test) als richtig anzusehen",
    22 => "ok, f&uuml;r die die IBAN ist (durch eine Regel) allerdings ein anderer BIC definiert",
    23 => "ok, f&uuml;r die BIC-Bestimmung der ehemaligen Hypo-Bank f&uuml;r IBAN wird i.A. zus&auml;tzlich die Kontonummer ben&ouml;tigt",
    24 => "ok, die Kontonummer wurde ersetzt, die neue Kontonummer hat keine Pr&uuml;fziffer",
    25 => "ok, es wurde ein (weggelassenes) Unterkonto angef&uuml;gt",
    26 => "ok, f&uuml;r den BIC wurde die Zweigstellennummer allerdings durch XXX ersetzt",
    27 => "ok, f&uuml;r den BIC wurde die Extension XXX angeh&auml;ngt",
    28 => "ok, f&uuml;r den BIC wurde die Wildcard-Version (8stellig) benutzt",
  }.freeze

  RETVAL_UNKNOWN_TEXT = "ungültiger Rückgabewert"
  RETVAL_UNKNOWN_SHORT = "ung?ltiger R?ckgabewert"
  LUT_BLOCK_TYPES = {
    1 => "BLZ",
    2 => "FILIALEN",
    3 => "NAME",
    4 => "PLZ",
    5 => "ORT",
    6 => "NAME_KURZ",
    7 => "PAN",
    8 => "BIC",
    9 => "PZ",
    10 => "NR",
    11 => "AENDERUNG",
    12 => "LOESCHUNG",
    13 => "NACHFOLGE_BLZ",
    14 => "NAME_NAME_KURZ",
    15 => "INFO",
    16 => "BIC_SORT",
    17 => "NAME_SORT",
    18 => "NAME_KURZ_SORT",
    19 => "ORT_SORT",
    20 => "PLZ_SORT",
    21 => "PZ_SORT",
    22 => "OWN_IBAN",
    23 => "VOLLTEXT_TXT",
    24 => "VOLLTEXT_IDX",
    25 => "IBAN_REGEL",
    26 => "IBAN_REGEL_SORT",
    27 => "BIC_H_SORT",
    28 => "SCL_INFO",
    29 => "SCL_BIC",
    30 => "SCL_NAME",
    31 => "SCL_FLAGS",
    32 => "SCL_FLAGS_ORIG",
    101 => "BLZ",
    102 => "FILIALEN",
    103 => "NAME",
    104 => "PLZ",
    105 => "ORT",
    106 => "NAME_KURZ",
    107 => "PAN",
    108 => "BIC",
    109 => "PZ",
    110 => "NR",
    111 => "AENDERUNG",
    112 => "LOESCHUNG",
    113 => "NACHFOLGE_BLZ",
    114 => "NAME_NAME_KURZ",
    115 => "INFO",
    116 => "BIC_SORT",
    117 => "NAME_SORT",
    118 => "NAME_KURZ_SORT",
    119 => "ORT_SORT",
    120 => "PLZ_SORT",
    121 => "PZ_SORT",
    122 => "OWN_IBAN",
    123 => "VOLLTEXT_TXT",
    124 => "VOLLTEXT_IDX",
    125 => "IBAN_REGEL",
    126 => "IBAN_REGEL_SORT",
    127 => "BIC_H_SORT",
    128 => "SCL_INFO",
    129 => "SCL_BIC",
    130 => "SCL_NAME",
    131 => "SCL_FLAGS",
    132 => "SCL_FLAGS_ORIG",
  }.freeze
end
