#!/usr/bin/env ruby
# frozen_string_literal: true

# Copyright (C) 2026 tickettoaster GmbH <https://tickettoaster.de>.
# Part of konto_check_ruby, a Ruby port of konto_check (Copyright (C)
# 2002-2023 Michael Plugge); licensed under the GNU Lesser General Public
# License, version 2.1 or later, see the file LICENSE.

# Differential test of the bank directory lookups (lut_* functions) against
# the C reference driver kc_ref: for every BLZ (and every branch) of the
# loaded LUT file all fields are compared.
#
# Usage:
#   ruby tools/difftest_lookup.rb KC_REF LUTFILE [RUBY_SOURCE]
#
# RUBY_SOURCE (optional) is a file the Ruby engine loads instead of LUTFILE:
# a LUT file generated by the Ruby port or a Bundesbank text file (then the
# C library reads LUTFILE and Ruby reads RUBY_SOURCE; used to verify the
# Ruby LUT writer and the Bundesbank file parser).

require "open3"
$LOAD_PATH.unshift File.expand_path("../lib", __dir__)
require "konto_check_ruby"

kc_ref = ARGV[0] or abort "usage: difftest_lookup.rb KC_REF LUTFILE [RUBY_SOURCE]"
lut = ARGV[1] or abort "LUT file missing"
ruby_source = ARGV[2] || lut

engine = KontoCheckRuby::Engine.new
code = if ruby_source =~ /\.(txt|csv|xml)\z/i
         engine.load_blz_file(ruby_source)
       else
         engine.init(ruby_source, 9)
       end
abort "init failed: #{code}" unless code > 0 || code == KontoCheckRuby::LUT2_PARTIAL_OK
data = engine.data

cases = []
data.cnt_hs.times do |i|
  blz = data.blz[i].to_s
  data.filialen_at(i).times { |k| cases << [blz, k] }
  cases << [blz, data.filialen_at(i)] # one out of range branch
end
cases += [["12345678", 0], ["1234567", 0], ["123456789", 0], ["1001001a", 0], [" 10010010", 0], ["10010010 x", 0]]

input = cases.map { |b, k| "A #{b} #{k}" }.join("\n") + "\n"
c_out, c_err, status = Open3.capture3(kc_ref, lut, "9", stdin_data: input)
abort "kc_ref failed: #{c_err}" unless status.success?
c_lines = c_out.lines.map(&:chomp)
abort "kc_ref returned #{c_lines.size} lines for #{cases.size} cases" unless c_lines.size == cases.size

def iso(s)
  s.nil? ? "(null)" : s.encode("ISO-8859-1", undef: :replace).force_encoding("UTF-8")
end

fails = 0
cases.each_with_index do |(blz, fil), i|
  f, r1 = engine.lut_filialen(blz)
  nm, r2 = engine.lut_name(blz, fil)
  nk, r3 = engine.lut_name_kurz(blz, fil)
  plz, r4 = engine.lut_plz(blz, fil)
  ort, r5 = engine.lut_ort(blz, fil)
  pan, r6 = engine.lut_pan(blz, fil)
  bic, r7 = engine.lut_bic(blz, fil)
  pz, r8 = engine.lut_pz(blz, fil)
  nr, r9 = engine.lut_nr(blz, fil)
  ae, r10 = engine.lut_aenderung(blz, fil)
  lo, r11 = engine.lut_loeschung(blz, fil)
  nb, r12 = engine.lut_nachfolge_blz(blz, fil)
  ir, r13 = engine.lut_iban_regel(blz, fil)
  rb = "#{r1} #{f}|#{r2} #{r2 == 1 ? nm : '(null)'}|#{r3} #{r3 == 1 ? nk : '(null)'}|#{r4} #{plz}|#{r5} #{r5 == 1 ? ort : '(null)'}|#{r6} #{pan}|" \
       "#{r7} #{bic.nil? ? '(null)' : bic}|#{r8} #{pz}|#{r9} #{nr}|#{r10} #{ae || '-'}|#{r11} #{lo.nil? ? '-' : lo}|#{r12} #{nb}|#{r13} #{ir}"
  c = c_lines[i].force_encoding("ISO-8859-1").encode("UTF-8")
  # the C library returns "" for name/ort in error cases; normalise
  c = c.gsub(/\|(-?\d+) (?=\|)/, '|\1 (null)')
  rb = rb.gsub(/\|(-?\d+) (?=\|)/, '|\1 (null)')
  next if rb == c
  fails += 1
  puts "MISMATCH blz=#{blz} filiale=#{fil}\n   C=[#{c}]\nRuby=[#{rb}]" if fails <= 40
end
puts "\nTested #{cases.size} lookups."
if fails.zero?
  puts "ALL OK"
else
  puts "#{fails} mismatches"
  exit 1
end
